### ISSUE TITLE
on-off socket status not updating in iOS home app not persistent 

### ISSUE THREAD

**Issue by BonRm** [macnow/homebridge-platform-orvibo#1]
hello, i installed the plugin and was hard for me to follow the instruciont to add each socket sending packet, today i turn the raspberry on and automatically discover all the sockets connected that was installed with widow app, i was so surprised, is this normal to discover automatically the sockets already installed trought wiwo app or I did something without realizing to do it? 

anyway, i noticed that the home app is not updating with the status of the sockets, if i turn on even the app display the socket on but if I close in background the home app (or completely close) and open it again all the sockets have off state again even if they are on, is a bug or what?
the terminal give me the right status instead of the off status for all the sockets but this status is not persistent in the home app like for the hue lights that even if i close the app and reopen the status is right, even with siri i can ask the status that for lights is working but for sockets is not working.
this is the terminal status: 
```
`root@raspberrypi:/home/pi# systemctl status -l  home bridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since dom 2016-10-16 14:46:27 CEST; 9min ago
 Main PID: 458 (home bridge
   CGroup: /system.slice/homebridge.service
           └─458 homebridge                                       

ott 16 14:50:55 raspberrypi homebridge[458]: [2016-10-16 14:50:55] State of Presa set to false
ott 16 14:50:55 raspberrypi homebridge[458]: [2016-10-16 14:50:55] State of Mac Socket set to true
ott 16 14:55:15 raspberrypi systemd[1]: Started Node.js HomeKit Server.
ott 16 14:55:39 raspberrypi homebridge[458]: [2016-10-16 14:55:39] State of Coffee Socket set to true
ott 16 14:55:39 raspberrypi homebridge[458]: [2016-10-16 14:55:39] State of Coffee Socket set to true
ott 16 14:55:39 raspberrypi homebridge[458]: [2016-10-16 14:55:39] State of Mac Socket set to true
ott 16 14:55:39 raspberrypi homebridge[458]: [2016-10-16 14:55:39] State of Raspberry Socket set to true
ott 16 14:55:39 raspberrypi homebridge[458]: [2016-10-16 14:55:39] State of Mac Socket set to true
ott 16 14:55:39 raspberrypi homebridge[458]: [2016-10-16 14:55:39] State of Raspberry Socket set to true
ott 16 14:55:39 raspberrypi homebridge[458]: [2016-10-16 14:55:39] State of Presa set to false
root@raspberrypi:/home/pi# 
`
```)

I have 4 socket connected but the terminal show the same socket more than once, why?

**Comment by jaquesp** [comment]
I see exactly the same thing. There is no persistence for the status of the Orvibo socket. I tried updating my version of node - thinking this was the issue. Can anyone help?

**Comment by macnow** [comment]
Could you check it with one socket?

**Comment by jaquesp** [comment]
@macnow Thanks for this - I'll check tonight!

**Comment by BonRm** [comment]
@macnow  just update and checked, everything is ok now, the status is persistent 👍 
 My Allone was detected even with the previous release but of course not working, are you planning to implement it? 
thanks

**Comment by macnow** [comment]
Ok, so I close this issue. Regarding Allone, I don't have this device, so I can't add support of this device, but stay tuned... I'm looking where I can buy it in Poland ;)

**Comment by jaquesp** [comment]
This worked first time for me also! Thanks so much @macnow !
